name: Static Analysis
on:
  push:
    branches:
      - chore/add-shellcheck-github-actions
  pull_request:
    paths:
      - '**.sh'
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Shellcheck
        run: shellcheck *.sh
