name: Static Analysis
on:
  pull_request:
    paths:
      - '**.sh'
  workflow_dispatch:
    inputs:
      exam:
        description: 'trial'
        required: false
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Shellcheck
        run: shellcheck *.sh
